#FROM pytorch/pytorch:latest
FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-devel
#FROM ubuntu:22.04
#FROM ubuntu:20.04

RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install -y \
        sudo \
        net-tools \
        python3.10 \
        python3-pip \
        libpython3.10 \
        build-essential \
        git \
        unzip \
        npm \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN usermod -aG sudo root

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    update-alternatives --config python3

WORKDIR /app/web
COPY web/package*.json ./
RUN npm install

COPY web/ .

#WORKDIR /app/api
#COPY api/ .

WORKDIR /app
RUN pwd
RUN ls -al

#RUN git clone https://github.com/ShadNygren/llama-cpp-python.git
RUN git clone --recurse-submodules https://github.com/ShadNygren/llama-cpp-python.git
#RUN cd llama-cpp-python
RUN pip3 install -e llama-cpp-python
#RUN cd ..

RUN ls -al

COPY setupenv.sh .
#RUN cd PAIAssistant
RUN chmod +x ./setupenv.sh
RUN ./setupenv.sh
# install -r requirements.txt is being done at the end of setupenv.sh
#RUN pip install -r requirements.txt

RUN pwd
RUN ls -al

# echo installing AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli2.zip"
RUN unzip -q awscli2.zip
RUN ./aws/install
RUN aws --version
RUN echo "$AWS_DEFAULT_REGION"
RUN aws configure set default.region "$AWS_DEFAULT_REGION"

RUN curl "https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb" -o "amazon-cloudwatch-agent.deb"
RUN dpkg -i -E amazon-cloudwatch-agent.deb

EXPOSE 4000
#EXPOSE 7860

ENV OPENAI_API_KEY <SAMPLE_OPENAI_API_KEY>

WORKDIR /app/web
CMD ["sh", "-c", "npm start"]

