#FROM pytorch/pytorch:latest
FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-devel

RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install -y \
        net-tools \
        python3.10 \
        python3-pip \
        build-essential \
        git \
        cuda-toolkit \
        libasound2-dev \
        npm \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    update-alternatives --config python3

RUN find / -name "*cuda*"
RUN find / -name "*cuBLAS*"
RUN find / -name "nvcc"
RUN nvidia-smi

WORKDIR /app/web
COPY web/package*.json ./
RUN npm install

COPY web/ .

WORKDIR /app/api
COPY api/ .

COPY setupenv.sh .
#RUN cd PAIAssistant
RUN chmod +x ./setupenv.sh
RUN ./setupenv.sh
# install -r requirements.txt is being done at the end of setupenv.sh
#RUN pip install -r requirements.txt

EXPOSE 4000
EXPOSE 7860

ENV OPENAI_API_KEY <SAMPLE_OPENAI_API_KEY>

CMD ["sh", "-c", "python api.py & npm start"]
