#FROM pytorch/pytorch:latest
FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-devel

RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install -y \
        net-tools \
        python3.10 \
        python3-pip \
        build-essential \
        git \
        unzip \
        #cuda-toolkit \
        libasound2-dev \
        npm \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    update-alternatives --config python3

RUN find / -name "*cuda*"
RUN find / -name "*cuBLAS*"
RUN find / -name "nvcc"
#RUN nvidia-smi

WORKDIR /app/web
COPY web/package*.json ./
RUN npm install

COPY web/ .

WORKDIR /app/api
#COPY api/ .
COPY api/ api/

COPY setupenv.sh .
#RUN cd PAIAssistant
RUN chmod +x ./setupenv.sh
RUN ./setupenv.sh
# install -r requirements.txt is being done at the end of setupenv.sh
#RUN pip install -r requirements.txt

# echo installing AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli2.zip"
RUN unzip -q awscli2.zip
RUN ./aws/install
RUN aws --version

#Unable to checkin model files etc due to size, you have to copy them manually from huggingface openchat_3.5.Q4_K_M.gguf and wav2lip checkpoints from https://drive.google.com/drive/folders/1I-0dNLfFOSFwrfqjNa-SXuwaURHE5K4k and copy to api/checkpoints folder
RUN aws s3 cp s3://paiassistant/huggingface/TheBloke/openchat_3.5-GGUF/blob/main/openchat_3.5.Q4_K_M.gguf api/checkpoints/
RUN aws s3 cp s3://paiassistant/wav2lip/wav2lip_gan.pth api/checkpoints/
RUN aws s3 cp s3://paiassistant/wav2lip/wav2lip.gif api/checkpoints/
RUN aws s3 cp s3://paiassistant/wav2lip/test.wav api/checkpoints/

#I have not uploaded the transcripts to github, i can provide a zip file to shared drive so you can move them over for indexing using createindex.py after dropping it to data\kwaai

EXPOSE 4000
EXPOSE 7860

ENV OPENAI_API_KEY <SAMPLE_OPENAI_API_KEY>

CMD ["sh", "-c", "python api.py & npm start"]
